apiVersion: v1
kind: Secret
metadata:
  name: hubble-proposer-private-key
data:
  # This is the default Account #0 geth private key
  # echo -n "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80" | base64
  privateKey: MHhhYzA5NzRiZWMzOWExN2UzNmJhNGE2YjRkMjM4ZmY5NDRiYWNiNDc4Y2JlZDVlZmNhZTc4NGQ3YmY0ZjJmZjgw
